name: Laravel

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  laravel-tests:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1

    - name: Copy file via scp
      uses: appleboy/ssh-action
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
